#
# @Cache-Control: no-store
# @infer true
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX calli: <http://callimachusproject.org/rdf/2009/framework#>
PREFIX screener: <https://probabilitytrading.net/screener/2014/schema.ttl#>

SELECT ?iri ?label ?comment ?profile
        ?forIndicator ?differenceFrom ?percentOf
        ?forWatchIndicator ?differenceFromWatch ?percentOfWatch
        ?lower ?upper {
    ?p foaf:name ?profile ;
        foaf:member <$user> ;
        calli:hasComponent ?iri .
    ?iri a screener:Criteria;
        rdfs:label ?label .
    OPTIONAL {
        ?iri rdfs:comment ?comment
    } OPTIONAL {
        ?iri screener:forIndicator ?forIndicator
    } OPTIONAL {
        ?iri screener:forWatchIndicator ?forWatchIndicator
    } OPTIONAL {
        ?iri screener:differenceFrom ?differenceFrom
    } OPTIONAL {
        ?iri screener:differenceFromWatch ?differenceFromWatch
    } OPTIONAL {
        ?iri screener:percentOf ?percentOf
    } OPTIONAL {
        ?iri screener:percentOfWatch ?percentOfWatch
    } OPTIONAL {
        ?iri screener:lower ?lower
    } OPTIONAL {
        ?iri screener:upper ?upper
    }
    BIND (coalesce(?correlatedBool, false) AS ?correlated)
}
