#
# @Cache-Control: no-store
# @infer true
# @view 
#
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX screener: <https://probabilitytrading.net/screener/2014/schema.ttl#>

SELECT ?iri ?label ?comment ?expression ?hasInterval ?hasUnit {
    ?iri a <../classes/Indicator>;
        rdfs:label ?label;
        rdfs:comment ?comment;
        screener:expression ?expression;
        screener:hasInterval ?hasInterval;
        screener:hasUnit ?hasUnit .
} ORDER BY ?label ?iri
